language: node_js
node_js:
  - 13
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  #tagging
  - docker tag udagram-api-feed quangkha91/udagram-api-feed:v3
  - docker tag udagram-api-user quangkha91/udagram-api-user:v3
  - docker tag udagram-frontend quangkha91/udagram-frontend:v3
  - docker tag reverseproxy quangkha91/reverseproxy:v3
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quangkha91/udagram-api-feed:v3
  - docker push quangkha91/udagram-api-user:v3
  - docker push quangkha91/udagram-frontend:v3
  - docker push quangkha91/reverseproxy:v3